const { GoogleGenAI } = require("@google/genai");
const puppeteer = require("puppeteer");
const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const responseSchema = {
  type: "OBJECT",
  properties: {
    matchScore: {
      type: "NUMBER",
      minimum: 0,
      maximum: 100,
    },

    technicalQuestions: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          question: {
            type: "STRING",
          },
          intention: {
            type: "STRING",
          },
          answer: {
            type: "STRING",
          },
        },
        required: ["question", "intention", "answer"],
      },
    },

    behavioralQuestions: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          question: {
            type: "STRING",
          },
          intention: {
            type: "STRING",
          },
          answer: {
            type: "STRING",
          },
        },
        required: ["question", "intention", "answer"],
      },
    },

    skillGaps: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          skill: {
            type: "STRING",
          },
          severity: {
            type: "STRING",
            enum: ["low", "medium", "high"],
          },
        },
        required: ["skill", "severity"],
      },
    },

    preparationPlan: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          day: {
            type: "NUMBER",
          },
          focus: {
            type: "STRING",
          },
          tasks: {
            type: "ARRAY",
            items: {
              type: "STRING",
            },
          },
        },
        required: ["day", "focus", "tasks"],
      },
    },
    title:{
      type: "STRING"
    }
  },

  required: [
    "matchScore",
    "technicalQuestions",
    "behavioralQuestions",
    "skillGaps",
    "preparationPlan",
    "title"
  ],
};

async function generateInterviewReport({jobDescription,resume,selfDescription})
{
    const prompt = `
Generate an interview preparation report for the candidate.

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}

Instructions:
- Follow the provided JSON schema exactly.
- Return ONLY valid JSON.
- technicalQuestions must be an array of objects.
- behavioralQuestions must be an array of objects.
- skillGaps must be an array of objects.
- preparationPlan must be an array of objects.
- Do not stringify objects.
- Do not include markdown.
- Do not include explanations outside JSON.
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema,
        temperature: 0.4,
      },
    });

   const report = JSON.parse(response.text);
   return report;
}

async function convertHtmlToPdf(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4',margin:{top:"20mm",bottom:"20mm",left:"15mm",right:"15mm"},border:"none" });
  await browser.close();
  return pdfBuffer;
}
async function generateResumePdf({resume,selfDescription,jobDescription}){
  const resumePdfSchema = {
  type: "OBJECT",
  properties: {
    html: {
      type: "STRING",
      description:
        "The HTML content of the resume which can be converted to PDF",
    },
  },
  required: ["html"],
};
  const prompt = `
Generate an HTML formatted resume based on the following information which can be converted to PDF using any library like Puppeteer:
Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}
The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
`
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: resumePdfSchema,
      temperature: 0.4,
    },
  });
  const pdfContent = JSON.parse(response.text);
  const pdfBuffer = await convertHtmlToPdf(pdfContent.html);
  return pdfBuffer;
} 
module.exports = {
  generateInterviewReport,
  generateResumePdf,
  
};